### ISSUE TITLE
Unable to plot -marginal for catalog with some fluxes=0

### ISSUE THREAD

**Issue by lukasfurtak** [jacopo-chevallard/PyP-BEAGLE#39]
Hi Jacopo,

I get this kind of `ValueError` whenever I try running `pyp_beagle --plot-marginal` for a sample of BEAGLE-outputs from a BEAGLE-input catalog containing some fluxes with value 0 (e.g. upper limits). This can easily be worked around by setting fluxes to ridiculously small values instead of zero, but maybe it is still worth looking in to.

```
/home/angers1NS/furtak/miniconda3/envs/beagle/lib/python2.7/site-packages/pyp_beagle/beagle_photometry.py:82: RuntimeWarning: divide by zero encountered in float_scalars
  flux_err[j] = (np.sqrt((flux_err[j]/flux[j])**2 +
/home/angers1NS/furtak/miniconda3/envs/beagle/lib/python2.7/site-packages/pyp_beagle/beagle_photometry.py:84: RuntimeWarning: invalid value encountered in double_scalars
  abs(flux[j]))
/home/angers1NS/furtak/miniconda3/envs/beagle/lib/python2.7/site-packages/pyp_beagle/beagle_photometry.py:223: RuntimeWarning: invalid value encountered in greater
  ok = np.where(obs_flux_err > 0.)[0]
/nethome/furtak/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
Traceback (most recent call last):
  File "/home/angers1NS/furtak/miniconda3/envs/beagle/bin/pyp_beagle", line 11, in <module>
    sys.exit(main())
  File "/home/angers1NS/furtak/miniconda3/envs/beagle/lib/python2.7/site-packages/pyp_beagle/command_line.py", line 248, in main
    my_photometry.plot_marginal(ID)
  File "/home/angers1NS/furtak/miniconda3/envs/beagle/lib/python2.7/site-packages/pyp_beagle/beagle_photometry.py", line 386, in plot_marginal
    ax.set_ylim([yMin, yMax])
  File "/home/angers1NS/furtak/miniconda3/envs/beagle/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 3457, in set_ylim
    bottom = self._validate_converted_limits(bottom, self.convert_yunits)
  File "/home/angers1NS/furtak/miniconda3/envs/beagle/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 3068, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf
```

**Comment by lukasfurtak** [comment]
Update: Setting the fluxes to 1e-7 instead of 0 works really well for plotting. I now always use two photometry catalogs, one for fitting and one for plotting (with 1e-7 instead of 0). It works fine, one just has to change the name of the photomrtic catalog name in the BEAGLE parameter file contained in the `BEAGLE-input-files` directory in each BEAGLE output directory.
