### ISSUE TITLE
Axis limits cannot be NaN or Inf

### ISSUE THREAD

**Issue by jacopo-chevallard** [jacopo-chevallard/PyP-BEAGLE#54]
This error is raised for some objects, specifically for spectra containing 0-valued fluxes

```
INFO:root:Computing the marginal plot for object ID: 10056849
WARNING:root:The `redshift` of the object is not unique!
/mnt/globalNS/tmp/charlot/lib/python3.6/site-packages/pyp_beagle/beagle_spectra.py:870: RuntimeWarning: divide by zero encountered in true_divide
  residual = (data_flux_-median_flux) / data_flux_err_
Traceback (most recent call last):
  File "/mnt/globalNS/tmp/charlot/bin/pyp_beagle", line 11, in <module>
    sys.exit(main())
  File "/mnt/globalNS/tmp/charlot/lib/python3.6/site-packages/pyp_beagle/command_line.py", line 262, in main
    my_spectrum.plot_marginal(ID, file_names[i])
  File "/mnt/globalNS/tmp/charlot/lib/python3.6/site-packages/pyp_beagle/beagle_spectra.py", line 929, in plot_marginal
    autoscale.autoscale_y(ax)
  File "/mnt/globalNS/tmp/charlot/lib/python3.6/site-packages/pyp_beagle/dependencies/autoscale.py", line 71, in autoscale_y
    ax.set_ylim(bot,top)
  File "/mnt/globalNS/tmp/charlot/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 3565, in set_ylim
    bottom = self._validate_converted_limits(bottom, self.convert_yunits)
  File "/mnt/globalNS/tmp/charlot/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 3211, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf
```

**Comment by jacopo-chevallard** [comment]
@scharlot cc @eclake this should fix the errors related to NaN / Inf values, can you test it? I tried with object 10056849 and it worked well

**Comment by scharlot** [comment]
@jacopo-chevallard thanks! You mean by upgrading pyp_beagle?
