### ISSUE TITLE
KeyError: "Extension 'marginal photometry' not found.", KeyError: "Extension 'apparent magnitudes' not found."

### ISSUE THREAD

**Issue by chavezoscar009** [jacopo-chevallard/PyP-BEAGLE#55]
Howdy Pyp-Beagle Team!!

I am running into some issues when trying to do a marginal plot. I have used the following command:

pyp_beagle -r results/Jorge_Galaxy --plot-marginal --log-wavelength

At some point the program crashes and it seems to be reading in the spectra file to get the model_sed and model_photometry but looks like there is no extension marginal photometry or apparent magnitudes in the spectra file

Here is the full error message I get: 

pyp_beagle -r results/Jorge_Galaxy --plot-marginal --log-wavelength 

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/pyp_beagle/beagle_photometry.py", line 234, in plot_marginal
    model_sed = hdulist['marginal photometry']
                ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 380, in __getitem__
    super().__getitem__, self._positive_index_of(key)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 847, in _positive_index_of
    index = self.index_of(key)
            ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 829, in index_of
    raise KeyError(f"Extension {key!r} not found.")
KeyError: "Extension 'marginal photometry' not found."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/pyp_beagle", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pyp_beagle/command_line.py", line 270, in main
    my_photometry.plot_marginal(ID)
  File "/opt/anaconda3/lib/python3.11/site-packages/pyp_beagle/beagle_photometry.py", line 237, in plot_marginal
    model_sed = hdulist['apparent magnitudes']
                ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 380, in __getitem__
    super().__getitem__, self._positive_index_of(key)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 847, in _positive_index_of
    index = self.index_of(key)
            ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 829, in index_of
    raise KeyError(f"Extension {key!r} not found.")
KeyError: "Extension 'apparent magnitudes' not found."

Any idea what could have caused this and I am unsure if this is a Pyp-Beagle issue or a BEAGLE issue?

**Comment by jacopo-chevallard** [comment]
@chavezoscar009 which pyp-beagle version are you using? `pyp_beagle --version` 

Also, can you copy here your Beagle parameter file?

**Comment by chavezoscar009** [comment]
Yeah for sure, I have attached the parameter file here and this is the pyp_beagle version that I have: 
pyp_beagle 0.10.16 - Author: Jacopo Chevallard

[Jorges_Fit.docx](https://github.com/jacopo-chevallard/PyP-BEAGLE/files/15323696/Jorges_Fit.docx)

**Comment by jacopo-chevallard** [comment]
If you update pyp_begale to the latest version `pip install -U pyp-beagle` you should not see an error anymore

In your parameter file, you should change
```
PRINT PHOTOMETRY = F
``` 
to
```
PRINT PHOTOMETRY = T
```

**Comment by chavezoscar009** [comment]
Ah gotcha, so I'll update to the latest pyp_beagle and then rerun beagle with the print photometry switch = T

**Comment by chavezoscar009** [comment]
Hey Jacopo, that update and adding in the T switch in the params file seems to have done the trick. Thanks for the help!!

**Comment by jacopo-chevallard** [comment]
great, closing then!
